profile: postgresql
resourceName: ${{ values.resourceName }}
implementation:
  path: resource/postgresql
postgresVersion: ${{ values.postgresVersion }}
instances:
  replicas: ${{ values.replicaCount }}
storage:
  storageClass: ${{ values.storageClass }}
user:
  name: ${{ values.userName }}
  database: ${{ values.databaseName }}
