apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: payments
  namespace: payments
  title: '[TEST] Payments Provider Domain'
  description: Cross-Domain API provider used only by Component integration tests.
  annotations:
    contract-first-idp.github.io/scm-provider: github
    contract-first-idp.github.io/scm-host: github.com
    contract-first-idp.github.io/domain-org: contract-first-idp
    contract-first-idp.github.io/domain-repo: software-templates
spec:
  owner: group:default/cf-idp-integration-tests-maintainers
  platformTarget: resource:default/workshop
  groupId: io.github.cfidp
  environments:
    order: [dev, test, prod]
    build: dev
    definitions:
      dev: {namespaceSuffix: -dev}
      test: {namespaceSuffix: -test}
      prod: {namespaceSuffix: ''}
