apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.system_name }}-${{ values.component_id }}-qa
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: ${{ values.system_name }}
spec:
  project: default
  source:
    repoURL: https://github.com/${{ values.git_org }}/developer-charts
    targetRevision: HEAD
    path: spring-boot-application
    helm:
      values: |
        system: ${{ values.system_name }}
        component: ${{ values.component_id }}
        environment: qa
        image:
          tag: latest
        replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.system_name }}-qa
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m