apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.systemName }}
  title: ${{ values.systemName }}
  description: ${{ values.description }}
  annotations:
    contract-first-idp.github.io/scm-provider: ${{ values.scmProvider }}
    contract-first-idp.github.io/scm-host: ${{ values.scmHost }}
    contract-first-idp.github.io/domain-org: ${{ values.domainOrg }}
    contract-first-idp.github.io/domain-repo: ${{ values.domainRepo }}
    contract-first-idp.github.io/repository-name: ${{ values.repositoryName }}
spec:
  owner: ${{ values.owner }}
  domain: ${{ values.domainRef }}
  groupId: ${{ values.groupId }}
