<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.16</version>
        <relativePath/>
    </parent>
    <groupId>${{ values.group_id }}</groupId>
    <artifactId>${{ values.component_id }}</artifactId>
    <packaging>jar</packaging>
    <name>${{ values.component_id }}</name>
    <version>1.0.0-SNAPSHOT</version>
    <properties>
        <java.version>21</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <apicurio.registry.maven.plugin.version>3.2.5.redhat-00004</apicurio.registry.maven.plugin.version>
        <schema.registry.api.url>${{ values.schema_registry_api_url }}</schema.registry.api.url>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <!-- Bean Validation API support -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
      <resources>
        <resource>
          <directory>${project.build.directory}/generated-resources/openapi</directory>
        </resource>
        <resource>
          <directory>src/main/resources</directory>
        </resource>
      </resources>
      <plugins>
        {%- if values.provided_api or values.consumed_apis | length > 0 %}
        <plugin>
          <groupId>io.apicurio</groupId>
          <artifactId>apicurio-registry-maven-plugin</artifactId>
          <version>${apicurio.registry.maven.plugin.version}</version>
          <executions>
            <execution>
              <id>download-openapi-contracts</id>
              <phase>initialize</phase>
              <goals><goal>download</goal></goals>
              <configuration>
                <registryUrl>${schema.registry.api.url}</registryUrl>
                <artifacts>
                  {%- if values.provided_api %}
                  <artifact>
                    <groupId>${{ values.provided_api.registry_group_id }}</groupId>
                    <artifactId>${{ values.provided_api.registry_artifact_id }}</artifactId>
                    {%- if values.provided_api.version != 'latest' %}
                    <version>${{ values.provided_api.version }}</version>
                    {%- endif %}
                    <file>${project.build.directory}/generated-resources/openapi/${{ values.provided_api.contract_file }}</file>
                    <overwrite>true</overwrite>
                  </artifact>
                  {%- endif %}
                  {%- for consumed_api in values.consumed_apis %}
                  <artifact>
                    <groupId>${{ consumed_api.registry_group_id }}</groupId>
                    <artifactId>${{ consumed_api.registry_artifact_id }}</artifactId>
                    {%- if consumed_api.version != 'latest' %}
                    <version>${{ consumed_api.version }}</version>
                    {%- endif %}
                    <file>${project.build.directory}/generated-resources/openapi/${{ consumed_api.contract_file }}</file>
                    <overwrite>true</overwrite>
                  </artifact>
                  {%- endfor %}
                </artifacts>
              </configuration>
            </execution>
          </executions>
        </plugin>
        {%- endif %}
        {%- if values.provided_api or values.consumed_apis | length > 0 %}
        <plugin>
          <groupId>org.openapitools</groupId>
          <artifactId>openapi-generator-maven-plugin</artifactId>
          <version>7.8.0</version>
          <executions>
              {%- if values.provided_api %}
              <execution>
                  <id>producer-spec</id>
                  <phase>generate-sources</phase>
                  <goals>
                      <goal>generate</goal>
                  </goals>
                  <configuration>
                      <generatorName>spring</generatorName>
                      <library>spring-boot</library>
                      <output>${project.basedir}/target/generated-sources</output>
                      <inputSpec>
                          ${project.build.directory}/generated-resources/openapi/${{ values.provided_api.contract_file }}
                      </inputSpec>
                      <generateModels>true</generateModels>
                      <generateModelDocumentation>false</generateModelDocumentation>
                      <generateModelTests>false</generateModelTests>
                      <generateApis>false</generateApis>
                      <generateSupportingFiles>false</generateSupportingFiles>

                      <configOptions>
                          <artifactId>${project.artifactId}</artifactId>
                          <groupId>${project.groupId}</groupId>
                          <version>${project.version}</version>
                          <useSpringBoot3>true</useSpringBoot3>
                          <dateLibrary>java8</dateLibrary>
                          <sourceFolder>src/main/java</sourceFolder>
                          <basePackage>${{ values.java_package }}</basePackage>
                          <generateApis>false</generateApis>
                          <modelPackage>${{ values.java_package }}.model</modelPackage>
                          <documentationProvider>none</documentationProvider>
                          <useSpringController>true</useSpringController>
                      </configOptions>
                  </configuration>
              </execution>
              {%- endif %}
              {%- for consumed_api in values.consumed_apis %}
              <execution>
                  <id>consumer-${{ consumed_api.alias }}</id>
                  <phase>generate-sources</phase>
                  <goals>
                      <goal>generate</goal>
                  </goals>
                  <configuration>
                      <generatorName>spring</generatorName>
                      <library>spring-boot</library>
                      <output>${project.basedir}/target/generated-sources/${{ consumed_api.alias }}</output>
                      <inputSpec>
                          ${project.build.directory}/generated-resources/openapi/${{ consumed_api.contract_file }}
                      </inputSpec>
                      <generateModels>true</generateModels>
                      <generateModelDocumentation>false</generateModelDocumentation>
                      <generateModelTests>false</generateModelTests>
                      <generateApis>false</generateApis>
                      <generateSupportingFiles>false</generateSupportingFiles>

                      <configOptions>
                          <artifactId>${project.artifactId}</artifactId>
                          <groupId>${project.groupId}</groupId>
                          <version>${project.version}</version>
                          <useSpringBoot3>true</useSpringBoot3>
                          <dateLibrary>java8</dateLibrary>
                          <sourceFolder>src/main/java</sourceFolder>
                          <basePackage>${{ values.java_package }}.client.${{ consumed_api.alias | replace('-', '') }}</basePackage>
                          <generateApis>false</generateApis>
                          <modelPackage>${{ values.java_package }}.client.${{ consumed_api.alias | replace('-', '') }}.model</modelPackage>
                          <documentationProvider>none</documentationProvider>
                          <interfaceOnly>true</interfaceOnly>
                      </configOptions>
                  </configuration>
              </execution>
              {%- endfor %}
          </executions>
        </plugin>
        {%- endif %}
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <configuration>
            <release>${java.version}</release>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
        </plugin>
      </plugins>
    </build>

    <pluginRepositories>
      <pluginRepository>
        <id>redhat-ga</id>
        <url>https://maven.repository.redhat.com/ga</url>
        <snapshots><enabled>false</enabled></snapshots>
      </pluginRepository>
    </pluginRepositories>

</project>
