apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: system-template
  title: System Template
  description: Create a System to contain a set of application Components, APIs, and Resources
spec:
  owner: backstage-admins
  type: system

  parameters:
    - title: Provide information on this application
      required:
        - system_name
        - owner
        - description
      properties:
        system_name:
          title: Name
          type: string
          description: Unique name of this application
        description:
          title: Description
          type: string
          description: System description
        owner:
          title: Owner
          type: string
          description: Owner of this applications
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
  steps:

    - id: fetch-domain
      name: fetch domain context
      action: catalog:fetch
      input:
        entityRef: domain:default/demo

    - id: system-template
      name: render system mainfiest
      action: fetch:template
      input:
        url: ./skeleton
        values:
          system_name: ${{ parameters.system_name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          git_org: ${{ steps['fetch-domain'].output.entity.metadata.labels['git-org'] }}

    - id: publish
      name: publish system manifest repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: GitOps manifest for ${{ parameters.system_name }}
        repoUrl: github.com?repo=${{ parameters.system_name }}-system&owner=${{ steps['fetch-domain'].output.entity.metadata.labels['git-org'] }}
        repoVisibility: public
        defaultBranch: main
        deleteBranchOnMerge: true
        protectDefaultBranch: false

    - id: register
      name: register system entity
      action: catalog:register
      input:
        repoContentsUrl: '${{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

    - id: domain-template
      name: render domain pull request
      action: fetch:template
      input:
        url: ./domain
        values:
          system_name: ${{ parameters.system_name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          git_org: ${{ steps['fetch-domain'].output.entity.metadata.labels['git-org'] }}
        targetPath: ./domain-gitops  

    - id: pr
      name: open domain pull request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=demo-domain&owner=${{ steps['fetch-domain'].output.entity.metadata.labels['git-org'] }}
        branchName: ${{ parameters.system_name }}
        title: add ${{ parameters.system_name }} system
        description: add ${{ parameters.system_name }} system
        sourcePath: ./domain-gitops

  output:
    links:
      - title: Pull Request to Domain
        url: ${{ steps.pr.output.remoteUrl }}
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}