apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentName }}
  title: ${{ values.componentName }}
  description: ${{ values.description }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.componentName }}
    contract-first-idp.github.io/scm-provider: ${{ values.scmProvider }}
    contract-first-idp.github.io/scm-host: ${{ values.scmHost }}
    contract-first-idp.github.io/domain-org: ${{ values.domainOrg }}
    contract-first-idp.github.io/domain-repo: ${{ values.domainRepo }}
    contract-first-idp.github.io/repository-name: ${{ values.repositoryName }}
    contract-first-idp.github.io/implementation-profile: ${{ values.implementationProfile }}
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.systemRef }}
{% if values.implementsApi %}
  providesApis:
    - ${{ values.apiRef }}
{% endif %}
{% if values.consumed_apis | length > 0 %}
  consumesApis:
{% for api in values.consumed_apis %}
    - ${{ api.ref }}
{% endfor %}
{% endif %}
