apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.api_id | dump}}
  title: ${{values.api_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/${{ values.system_name }}/spectral-rules/main/ruleset.yaml
  links:
    - url: ${{ values.service_registry_provider_url }}/ui/artifacts/${{ values.service_registry_group_id }}/${{ values.api_id }}/versions/latest
      title: Apicurio Registry
      icon: web
    - url: ${{ values.mock_provider_url }}/#/services?name=${{ values.api_id }}
      title: Microcks
    - url: ${{ values.mock_provider_url }}/rest/${{ values.api_id }}/v1
      title: Mock
      icon: web
spec:
  type: openapi
  system: system:default/${{values.system_name }}
  owner: ${{ values.owner }}
  lifecycle: production
  definition:
    $openapi: ${{ values.git_repo_url }}/blob/main/specification.yaml