replicas: 1
image:
  pullPolicy: ${{ 'Always' if values.environment == values.buildEnvironment else 'IfNotPresent' }}
route:
  enabled: true
runtime:
  health:
{% if 'quarkus' in values.implementationProfile %}
    readinessPath: /q/health/ready
    livenessPath: /q/health/live
    port: 8080
{% else %}
    readinessPath: /actuator/health/readiness
    livenessPath: /actuator/health/liveness
    port: 8081
{% endif %}
    initialDelaySeconds: 10
    periodSeconds: 10
  resources:
    requests: {cpu: 100m, memory: 256Mi}
    limits: {cpu: 500m, memory: 1Gi}
  envFromSecretNames: []
  env: []
