apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.system_name }}-${{ values.component_id }}-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: ${{ values.system_name }}
spec:
  project: default
  source:
    repoURL: https://github.com/${{ values.git_org }}/developer-charts
    targetRevision: HEAD
    path: spring-boot-pipeline
    helm:
      values: |
        domain: ${{ values.git_org }}
        system: ${{ values.system_name }}
        component: ${{ values.component_id }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.system_name }}-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m