apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.system_name}}-system-namespaces
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    system: ${{values.system_name}}
spec:
  project: default
  source:
    repoURL: https://github.com/${{values.git_org}}/developer-charts
    targetRevision: HEAD
    path: system-namespaces
    helm:
      values: |
        system: ${{values.system_name}}
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
